### ISSUE TITLE
Single node Opensearch on AWS result in error.

### ISSUE THREAD

**Issue by Barteus** [canonical/opensearch-operator#420]
## Steps to reproduce

1. Bootstrap juju on AWS
2. Deploy single node opensearch cluster using bundle
Bundle:
```
default-base: ubuntu@22.04/stable
applications:
  data-integrator:
    charm: data-integrator
    channel: latest/stable
    num_units: 1
    to:
    - "0"
    options:
      extra-user-roles: admin
      index-name: test-index
    constraints: arch=amd64
  opensearch:
    charm: opensearch
    channel: 2/edge
    num_units: 1
    to:
    - "0"
    constraints: arch=amd64
    storage:
      opensearch-data: rootfs,1,1024M
  self-signed-certificates:
    charm: self-signed-certificates
    channel: latest/stable
    num_units: 1
    to:
    - "0"
    options:
      ca-common-name: Demo CA
    constraints: arch=amd64
machines:
  "0":
    constraints: arch=amd64
relations:
- - self-signed-certificates:certificates
  - opensearch:certificates
- - data-integrator:opensearch
  - opensearch:opensearch-client
```

## Expected behavior
Opensearch is working.

## Actual behavior

```
Model  Controller      Cloud/Region   Version  SLA          Timestamp
os     aws-controller  aws/eu-west-1  3.5.3    unsupported  16:49:50Z

App                       Version  Status   Scale  Charm                     Channel        Rev  Exposed  Message
data-integrator                    active       1  data-integrator           latest/stable   41  no       
opensearch                         blocked      1  opensearch                2/edge         143  no       1 or more 'replica' shards are not assigned, please scale your application up.
self-signed-certificates           active       1  self-signed-certificates  latest/stable  155  no       

Unit                         Workload  Agent  Machine  Public address  Ports     Message
data-integrator/0*           active    idle   0        34.252.96.248             
opensearch/0*                active    idle   0        34.252.96.248   9200/tcp  
self-signed-certificates/0*  active    idle   0        34.252.96.248        
```

Additionally, I get timeout on all operations.

## Versions

Operating system: Ubuntu 22.04

Juju CLI: 3.5.3

Juju agent: 3.5.3

Charm revision: both 2/beta & 2/edge

LXD: nope - using AWS

## Log output

Juju debug log: 
[log.txt](https://github.com/user-attachments/files/16802802/log.txt)
