### ISSUE TITLE
OpenSearchBulkRequestsRejectionJumps alert is using an invalid expression

### ISSUE THREAD

**Issue by gabrielcocenza** [canonical/opensearch-operator#503]
Taking a look at the alerts, I saw that the `OpenSearchBulkRequestsRejectionJumps` has the following expression:

```yaml
  - "alert": "OpenSearchBulkRequestsRejectionJumps"
    "annotations":
      "message": "High Bulk Rejection Ratio at {{ $labels.node }} node in {{ $labels.cluster }} cluster. This node may not be keeping up with the indexing speed."
      "summary": "High Bulk Rejection Ratio - {{ $value }}%"
    "expr": |
      round( bulk:reject_ratio:rate2m * 100, 0.001 ) > 5
    "for": "10m"
    "labels":
      "severity": "warning"
```

The `bulk:reject_ratio:rate2m` is not recorded, do it's a metric that will never show up to trigger the alert.

Probably this alert was inspired on this [repo](https://github.com/lukas-vlcek/prometheus-elasticsearch-rules/blob/master/logging_elasticsearch.rules.yaml) and missed proper definition.
