### ISSUE TITLE
The default `base_path` setting for `s3-repository` is not correct

### ISSUE THREAD

**Issue by weiiwang01** [canonical/opensearch-operator#657]
When `path` is not set in the `s3-integrator`, the OpenSearch charm will use `"/"` as the value for the `s3-repository` `base_path` setting. This is problematic because OpenSearch will prepend the `/` to the object upload path. For example, the original path `/indices/_aZzRvw-RLimbp3SsTbXQw/meta-1kMKfpcB6Mg9Iz7fTcr5.dat` will be uploaded to the S3 bucket as `//indices/_aZzRvw-RLimbp3SsTbXQw/meta-1kMKfpcB6Mg9Iz7fTcr5.dat`, which will cause the S3 API to return an error response.

## Steps to reproduce

N/A

## Expected behavior
When `path` is not set in the `s3-integrator`, the OpenSearch charm should use `null` for the `s3-repository` `base_path` setting.

## Actual behavior
When `path` is not set in the `s3-integrator`, the OpenSearch charm uses `"/"` for the `s3-repository` `base_path` setting.

## Versions

Operating system: Ubuntu 24.04

Juju CLI: `3.6.7-genericlinux-amd64`

Juju agent: `3.6.2`

Charm revision: `234`

LXD: 

## Log output

[log.txt](https://github.com/user-attachments/files/20776971/log.txt)

## Additional context
`s3-integrator` relation data:

```yaml
  - relation-id: 88
    endpoint: s3-credentials
    related-endpoint: s3-credentials
    application-data:
      access-key: ****
      bucket: stg-opencti-db
      data: '{"bucket": "relation-88"}'
      endpoint: https://...
      region: us-east-1
      s3-uri-style: path
      secret-key: ****
    related-units:
      s3-integrator/7:
        in-scope: true
        data:
          egress-subnets: 10.142.156.5/32
          ingress-address: 10.142.156.5
          private-address: 10.142.156.5
```

OpenSearch `/_snapshot` output

```json
{
  "s3-repository" : {
    "type" : "s3",
    "settings" : {
      "bucket" : "stg-opencti-db",
      "path_style_access" : "true",
      "endpoint" : "https://...",
      "protocol" : "https",
      "storage_class" : null,
      "base_path" : "/",
      "region" : "us-east-1"
    }
  }
}
```
